name: abiola_along_client_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  reusables:
    git:
      url: https://github.com/SparkoSol/reusables.git
      ref: migration
  image_picker: ^1.1.2
  path_provider: ^2.0.7
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  retrofit: ^4.1.0
  riverpod_annotation: ^2.3.5
  riverpod: ^2.5.1
  intl: ^0.18.0
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.1
  file_picker: ^8.0.4
  flutter_native_splash: ^2.4.0
  skeletonizer: ^1.4.2
  cached_network_image: ^3.4.0
  fluttertoast: ^8.2.8
  auto_size_text: ^3.0.0
  url_launcher: ^6.3.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  camera: ^0.11.0+2
  custom_info_window: ^1.0.1

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  riverpod_lint: ^2.3.10
  freezed: ^2.4.7

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/



flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/app-logo.png
  image_dark: assets/images/app-logo.png
  color_dark: "#121825"
  android_12:
    color: "#FFFFFF"
    image: assets/images/app-logo.png
    image_dark: assets/images/app-logo.png
    color_dark: "#121825"
